# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'aws'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Build services'
          additionalImageTags: '$(Build.BuildNumber)'
          includeSourceTags: true
          includeLatestTag: true
      # - task: CopyFiles@2
      #   inputs:
      #     SourceFolder: 'src'
      #     Contents: |
      #       **/*.yml
      #       **/*.yaml
      #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: 'drop'
      #     publishLocation: 'Container'

      # # - task: ECRPushImage@1
      # #   inputs:
      # #     awsCredentials: 'aws dev'
      # #     regionName: 'us-east-1'
      # #     imageSource: 'imagename'
      # #     sourceImageName: 'tasklist-service'
      # #     sourceImageTag: '$(Build.BuildNumber)'
      # #     repositoryName: 'relay-dev'
      # #     pushTag: '$(Build.BuildNumber)'
      # #     autoCreateRepository: true
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: 'aws'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Push services'
          additionalImageTags: '$(Build.BuildNumber)'
          includeSourceTags: true
          includeLatestTag: true