# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: AWSCLI@1
      inputs:
        awsCredentials: 'aws dev'
        regionName: 'us-east-1'
        awsCommand: 'ecr'
        awsSubCommand: 'get-login'
        awsArguments: '|sh'

    - task: Docker@2
      inputs:
        containerRegistry: 'aws'
        repository: 'jovili/tasklist-web'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'aws'
    #     repository: 'jovili'
    #     command: 'build'
    #     Dockerfile: '**/Dockerfile'
        
    - task: Docker@2
      inputs:
        containerRegistry: 'aws'
        repository: 'jovili'
        command: 'push'
        tags: 
    # - task: ECRPushImage@1
    #   inputs:
    #     awsCredentials: 'aws dev'
    #     regionName: 'us-east-1'
    #     imageSource: 'imagename'
    #     sourceImageName: 'jovili/tasklist-web'
    #     sourceImageTag: '$(Build.BuildId)'
    #     repositoryName: 'jovili/tasklist-web'
    #     pushTag: '$(Build.BuildId)'
    #     autoCreateRepository: true
    #     logRequest: true
    #     logResponse: true

